### ISSUE TITLE
Incorrect Weibull reliability function?

### ISSUE THREAD

**Issue by jonjanisch** [felixreimann/jreliability#6]
Hello. I was just browsing through the source code of WeibullReliabilityFunction and believe it's not implemented correctly. This is completely outside my area of expertise and I have not downloaded or tried using jreliability so I'm likely wrong.

getY is implemented as follows:

`Math.exp(-(Math.pow((alpha * x), beta)));`

and is documented as:

`R(x) = 1 - F(x) = e^-((alpha * x)^beta))`

According to: http://reliawiki.org/index.php/The_Weibull_Distribution
...the reliability function should be:

`R(x) = 1 - F(x) = e^-((x/alpha)^beta))`

![Weibull](http://reliawiki.org/images/math/1/7/6/1766b0fdf5bbab362a61ff2fbc356b9f.png)

`Math.exp(-(Math.pow((x/alpha), beta)));`

**Comment by michaelhglass** [comment]
Hi,

[Short Answer: To highlight the similarity of Exponential and Weibull distributions, we unified the parameters, i.e. \alpha = \lambda = 1 / \nu.]

I think this is solely a matter of definition. If you check the standard definition of the Weibull distribution, you see \gamma just basically moves the absolut time to model failure-free times. So it all boils down to how to handle the 1 / \nu. In JReliability - and since different distributions use different variables for their standard parameters - we tried to use the parameter \alpha as a placeholder for sth. the corresponds to the failure rate which typically called \lambda. To highlight the similarity of ExponentialDistribution and WeibullDistribution, we used \alpha ~ \lambda instead of 1/\nu ~ \lambda.

Thanks for your comment, I will clarify this in the documentation of the Weibull distribution.

Best, Micha
